create sequence hibernate_sequence start 1 increment 1;

create table author
(
    id         int primary key generated by default as identity,
    first_name varchar(30) not null,
    last_name  varchar(30) not null
);

create table book
(
    id         int primary key generated by default as identity,
    title      varchar(100) not null,
    issue_year int          not null,
    amount     int          not null
);

create table author_book
(
    author_id int references author (id),
    book_id   int references book (id)
);

create table publisher
(
    id         int primary key generated by default as identity,
    first_name varchar(30) not null,
    last_name  varchar(30) not null
);

create table client
(
    id     int primary key generated by default as identity,
    amount int         not null,
    name   varchar(30) not null
);

create table book_client
(
    amount    int not null,
    book_id   int not null references book(id),
    client_id int not null references client(id)
);