-- INSERT INTO author (first_name, last_name)
-- values ('Test1', 'Test1');
-- INSERT INTO author (first_name, last_name)
-- values ('Test2', 'Test2');
-- INSERT INTO author (first_name, last_name)
-- values ('Test3', 'Test3');
-- INSERT INTO author (first_name, last_name)
-- values ('Test4', 'Test4');
-- INSERT INTO author (first_name, last_name)
-- values ('Test5', 'Test5');
--
-- INSERT INTO book (title, amount, isbn, issue_datetime)
-- VALUES ('Test1', 50, 1-1-1, '2020-06-22 19:10:25-07');
-- INSERT INTO book (title, amount, isbn, issue_datetime)
-- VALUES ('Test2', 50, 1-1-1, '2020-06-22 19:10:25-07');
-- INSERT INTO book (title, amount, isbn, issue_datetime)
-- VALUES ('Test3', 50, 1-1-1, '2020-06-22 19:10:25-07');
-- INSERT INTO book (title, amount, isbn, issue_datetime)
-- VALUES ('Test4', 50, 1-1-1, '2020-06-22 19:10:25-07');
-- INSERT INTO book (title, amount, isbn, issue_datetime)
-- VALUES ('Test5', 50, 1-1-1, '2020-06-22 19:10:25-07');
--
-- insert into client (amount, name)
-- values (20, 'Test1');
-- insert into client (amount, name)
-- values (20, 'Test2');
-- insert into client (amount, name)
-- values (20, 'Test3');
--
-- insert into publisher (first_name, last_name)
-- VALUES ('Test1', 'Test1');
-- insert into publisher (first_name, last_name)
-- VALUES ('Test2', 'Test2');
-- insert into publisher (first_name, last_name)
-- VALUES ('Test3', 'Test3');
--
-- -- insert into book_client (amount, book_id, client_id)
-- -- VALUES (12, 1, 2);
-- -- insert into book_client (amount, book_id, client_id)
-- -- VALUES (12, 2, 1);
-- -- insert into book_client (amount, book_id, client_id)
-- -- VALUES (12, 3, 5);